defaults: &defaults
  access_key_id: 'AKIAIDQ2YKFH75QBJLFQ'
  secret_access_key: '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'
development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
